### ISSUE TITLE
Can't reboot RPi with LinuxDECnet installed

### ISSUE THREAD

**Issue by cguldenschuh** [JohnForecast/LinuxDECnet#1]
HW: RPi 4B 2GB memory, USB boot
SW: Debian 12 (bookworm), clean install from Raspbian.com image
Kernel: 6.1.0-rpi4-rpi-v8

DECnet installed and working.  On reboot, get a loop of messages:

unregister_netdevice: waiting for eth0 to become free. Usage count = 2
eth0 selects TX queue 0, but real number of TX queues is 0

stopping decnet3.service before reboot doesn't help.

If decnet3.service is not enabled, and not started, reboot proceeds

**Comment by JohnForecast** [comment]
Thanks Chuck. I can reproduce it here, although I only get a single message - seems to be Bookworm specific on the Raspberry Pi.

  John.

**Comment by JohnForecast** [comment]
Now that dhcpcd is longer present in RaspiOS, how did you configure your ethernet device?

**Comment by cguldenschuh** [comment]
They certainly didn't make that straightforward...
I'm using NetworkManager, with all default settings.  Apparently, at some point in the boot process dhclient gets invoked.

**Comment by JohnForecast** [comment]
I added some code to get a callback when a system reboot is in progress and release a reference on the ethernet/wireless device. That should fix the problem you are seeing.

**Comment by cguldenschuh** [comment]
That seems to have fixed the problem!  Thanks
