### ISSUE TITLE
Can't read /proc/net/decnet_revision; file not found

### ISSUE THREAD

**Issue by vaxorcist** [JohnForecast/LinuxDECnet#10]
I installed LinuxDECnet 14. Sep 22:08:03 CEST 2024.
Today I wanted to see if there is a newer version and found 3.0.10 in LinuxDECnet/blob/master/README.DECnet at github.
When trying to read my installed version I got:
cat /proc/net/decnet_revision
cat: /proc/net/decnet_revision: Datei oder Verzeichnis nicht gefunden (= file not found)
I'm using vanilla Debian GNU/Linux 12 (bookworm).

**Comment by vaxorcist** [comment]
Is it possible that a major Debian system update
(including kernel) overwrites LinuxDECnet?

**Comment by vaxorcist** [comment]
Is it possible that a major Debian system update
(including kernel) overwrites LinuxDECnet?

**Comment by vaxorcist** [comment]
I fixed the problem myself re-executing BuildAndInstall.sh.
I think the kernel update was the cause.

**Comment by JohnForecast** [comment]
The DECnet kernel module (decnet3.ko) is created in the tree starting at: /lib/modules/<kernelVersion>. If you install an updated kernel version, the DECnet modules will not be found and, as you found, various files in /proc will not be created. There should have been an error message from dnetd in the systemd journal indicating the problem. Re-executing BuildAndInstall.sh will generate a new decnet3.ko associated with the running kernel.
