### ISSUE TITLE
phoned: 100% CPU usage even when not directly in use

### ISSUE THREAD

**Issue by jayjwa** [JohnForecast/LinuxDECnet#3]
phoned seems to pick up even when it's not being called. Consider:

```
#V001.0
#               DECnet hosts file
#
#Node           Node            Name            Node    Line    Line
#Type           Address         Tag             Name    Tag     Device
#-----          -------         -----           -----   -----   ------
executor	1.1		name            ATR2    line	br0
node		1.10 		name		DTSR
node		1.11 		name		KIRIN
node		1.12		name		KUSHAL
node		1.13 		name		TEOSTR
node		1.14 		name		LUNAST
node		1.15		name		NERGIG
```

Phoning from VMS nodes KUSHAL (%phone lunast::system) to LUNAST ($phone answer) should not involve Linux node ATR2, yet phoned hits 100% CPU use and stays up, even though it is not in use. It's not enough to slow the system significantly, but it is noticeable. 

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
32171 nobody    20   0    3036   2036   1908 S 100.0   0.0   0:30.49 phoned
```
At this point, phoned has to be pkill'd and restarted, even after the nodes are done with the call. Another phone will produce the same results. phoned is fine - as long as it doesn't see phone traffic on the LAN that isn't meant for it. phone to the Linux node works as expected. Another example:

`32479 nobody    20   0    3036   1536   1536 S 100.0   0.0   1:04.01 phoned`

There's nothing noteworthy in the logs, just that phoned is starting. No matter what the VMS nodes are doing, it shouldn't put the CPU to 100% on the Linux node since it's not actually involved. 
```
/usr/local/bin/node lunast
lunast has address 1.14
/usr/local/bin/node kushal
kushal has address 1.12
```
The packet capture shows the Linux node as well, 1.1. 
[phoned-100.pcap.gz](https://github.com/JohnForecast/LinuxDECnet/files/13629820/phoned-100.pcap.gz)

The same type of situation might be happening with ctermd as well, but for now let's look at phoned. This is decnet 3.0.4.

**Comment by JohnForecast** [comment]
This is caused by using a bridge as the network interface. Bridging causes the ethernet/wireless to be in promiscuous mode where all packets will be seen by the DECnet code. I was missing a check to discard unicast packets if they were not addressed to the local node. I've just checked in an update - this should show version 3.0.4

**Comment by jayjwa** [comment]
This fixes the issue, will close.
