### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by jayjwa** [JohnForecast/LinuxDECnet#8]
I'm creating a Slackbuild script (packaging) for Slackware. I've noticed a few minor issues. They may affect people packaging the source for other distros as well. 

- Non-executable solibs
Shared libraries are usually mode 0755 (but still work otherwise). You can see some being installed 644 here:
```
~/p/s/d/L/dnprogs (master)> find . -name Makefile -exec grep -H 'install -m 0644 $(STRIP
BIN) $(SHAREDLIB)' '{}' ';'
./libdaemon/Makefile:	install -m 0644 $(STRIPBIN) $(SHAREDLIB) $(libprefix)$(libdir)
./libdap/Makefile:	install -m 0644 $(STRIPBIN) $(SHAREDLIB) $(libprefix)$(libdir)
./libdnet/Makefile:	install -m 0644 $(STRIPBIN) $(SHAREDLIB) $(libprefix)$(libdir)/$(SHAREDLIB)
./librms/Makefile:	install -m 0644 $(STRIPBIN) $(SHAREDLIB) $(libprefix)$(libdir)
```

- node
https://nodejs.org/en Node.Js is a popular Javascript runtime environment, likely to be installed on many people's systems. This is the case with Slackware. It has a _/usr/bin/node_ binary. When Linux DECnet is packaged, it will likely be based on /usr and clobber _node_ with _node_.
```
usr/
usr/bin/
usr/bin/dncopy
usr/bin/dndel
usr/bin/dndir
usr/bin/dnetcat
usr/bin/dnetstat
usr/bin/dnlogin
usr/bin/dnping
usr/bin/dnsubmit
usr/bin/dntask
usr/bin/dts
usr/bin/node
usr/bin/phone
usr/bin/sethost
```
With a nod to _nslookup_, and keeping with the "dn" prefix, suggest to rename _node_ to _dnlookup_ along with its corresponding man page. Renaming the program would avoid this situation, and bring its name in line with its work-alike, _nslookup_.

- phone
When I built the project for release, I used _make RELEASE=1_ in the dnprogs subdir. Surprisingly, this resulted in _phone_ not running. It seems when RELEASE is defined, GTK checks are skipped, and _phone_ builds without GUI.

Built **without** RELEASE=1:
```
jayjwa@atr2 ~/p/s/d/L/d/phone (master)> ldd phone
        linux-vdso.so.1 (0x00007ffff7fc4000)
        libpanelw.so.6 => /lib64/libpanelw.so.6 (0x00007ffff7f76000)
        libncurses.so.6 => /lib64/libncurses.so.6 (0x00007ffff7f4a000)
        libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007ffff7f16000)
        libdnet.so.3 => /usr/lib64/libdnet.so.3 (0x00007ffff7f0d000)
        libgtk-1.2.so.0 => /usr/lib64/libgtk-1.2.so.0 (0x00007ffff7d87000)
        libgdk-1.2.so.0 => /usr/lib64/libgdk-1.2.so.0 (0x00007ffff7d43000)
        libgmodule-1.2.so.0 => /usr/lib64/libgmodule-1.2.so.0 (0x00007ffff7d3c000)
        libglib-1.2.so.0 => /usr/lib64/libglib-1.2.so.0 (0x00007ffff7d0b000)
        libXi.so.6 => /usr/lib64/libXi.so.6 (0x00007ffff7cf8000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007ffff7ce4000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007ffff7ba4000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ffff7abb000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffff7800000)
        libncursesw.so.6 => /lib64/libncursesw.so.6 (0x00007ffff7a7d000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ffff7a78000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007ffff7a50000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffff7fc6000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007ffff7a4b000)
        libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6 (0x00007ffff7a41000)
```
(working)

Built **with** make RELEASE=1:
```
jayjwa@atr2 ~/p/s/d/L/d/phone (master)> ldd phone
        linux-vdso.so.1 (0x00007ffff7fc4000)
        libpanelw.so.6 => /lib64/libpanelw.so.6 (0x00007ffff7f76000)
        libncurses.so.6 => /lib64/libncurses.so.6 (0x00007ffff7f4a000)
        libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007ffff7f16000)
        libdnet.so.3 => /usr/lib64/libdnet.so.3 (0x00007ffff7f0d000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffff7c00000)
        libncursesw.so.6 => /lib64/libncursesw.so.6 (0x00007ffff7ed1000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ffff7eca000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffff7fc6000)

%fish: Job 1, './phone' terminated by signal SIGSEGV (Address boundary error)
%
 Program received signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  0x00007ffff7f6c47e in ?? () from /lib64/libncurses.so.6
#1  0x00007ffff7f6c981 in wresize () from /lib64/libncurses.so.6
#2  0x0000000000402bf9 in rearrange_windows ()
#3  0x0000000000402cca in new_talk_window ()
#4  0x0000000000403a21 in ncurses_run ()
#5  0x00000000004026b2 in main ()
(gdb)
```
(not working)
That is, the TUI _phone_ doesn't seem to run while the GUI one does. Slackware updated ncurses not too long ago (though I only used the GUI _phone_ before), so maybe that's the issue. I thought I'd poinit it out.

**Comment by JohnForecast** [comment]
1. I've renamed the "node" program to "dnnode".

2. There seems to be some disagreement about the protection codes for shared libraries; Debian and derivatives use 0644 while Fedora and derivatives use 0755.

3. Most of my systems are headless so I end up using the TUI version which runs fine on RaspiOS (a Debian 12 derivative). As far as I can see, adding "RELEASE=1" enables GTK checking based on the original rewlease of GTK - my non-headless systems are running GTK4 and there is no gtk-config present. Do you have it on your system?

**Comment by jayjwa** [comment]
Excellent. I was not aware of solibs intentionally being 644 sometimes. Yes, I have GTK1-4 including 1.2 so phone is GUI here. I suspect a local issue with ncurses as the build format changed awhile ago from what Slackware used to do. I'll have to check into that further.
